export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Nested layouts in the App Router must not include <html> or <body> tags
  return (
    <section>
      {children}
    </section>
  )
}
